'use strict';

var to_be_iru = [
  new Term(['いる'], [''], 'to be (animate)'),
];

var to_be_aru = [
  new Term(['ある'], [''], 'to be (inanimate)'),
];

var irregular_suru = [
  new Term(['する'], [''], 'to do'),
];

var irregular_kuru = [
  new Term(['く','る'], ['来',''], 'to come'),
];

var verbs_ichidan = [
  new Term(['あ','ける'], ['開',''], 'to open'),
  new Term(['あげる'], [''], 'to give'),
  new Term(['あつ','める'], ['集',''], 'to gather; to collect'),
  new Term(['あ','びる'], ['浴',''], 'to bathe; to take a shower'),
  new Term(['あわ','てる'], ['慌',''], 'to panic; to be flustered'),
  new Term(['い','い','つ','ける'], ['言','','付',''], 'to command; to order; to tell on someone'),
  new Term(['い','きる'], ['生',''], 'to be alive'),
  new Term(['いじ','める'], ['虐',''], 'to torment; to bully'),
  new Term(['いまし','める'], ['戒',''], 'to admonish'),
  new Term(['い','る'], ['居',''], 'to exist; to be'),
  new Term(['い','れる'], ['入',''], 'to insert; to put in'),
  new Term(['う','まれる'], ['生',''], 'to be born'),
  new Term(['え','る'], ['得',''], 'to obtain; to get'),
  new Term(['お','きる'], ['起',''], 'to wake up; to occur'),
  new Term(['おく','れる'], ['遅',''], 'to be late; to lag behind'),
  new Term(['おさ','える'], ['抑',''], 'to restrain; to control'),
  new Term(['おし','える'], ['教',''], 'to teach; to inform'),
  new Term(['おそ','れる'], ['恐',''],  'to fear'),
  new Term(['お','ちる'], ['落',''], 'to fall; to fail'),
  new Term(['おぼ','える'], ['覚',''], 'to remember; to learn'),
  new Term(['お','りる'], ['降',''], 'to alight, to descend'),
  new Term(['お','れる'], ['折',''], 'to be broken; to snap'),
  new Term(['か','える'], ['変',''], 'to change'),
  new Term(['か','える'], ['換',''], 'to change (clothes)'),
  new Term(['かか','える'], ['抱',''], 'to hold (in your arms), have'),
  new Term(['かか','げる'], ['掲',''], 'to raise (a flag); to hold up'),
  new Term(['かける'], [''], 'to hang; to call on the phone; to risk'),
  new Term(['かさ','ねる'], ['重',''], 'to pile up; to repeat'),
  new Term(['かぞ','える'], ['数',''], 'to count'),
  new Term(['かた','づ','ける'], ['片','付','ける'], 'to finish; to tidy up'),
  new Term(['かた','める'], ['固',''], 'to strengthen; to harden'),
  new Term(['かま','える'], ['構',''], 'to set up; to prepare in advance'),
  new Term(['か','りる'], ['借',''], 'to borrow; to rent'),
  new Term(['か','れる'], ['枯',''],  'to wither'),
  new Term(['かんが','える'], ['考',''], 'to think'),
  new Term(['かん','じる'], ['感',''], 'to feel; to sense'),
  new Term(['き','える'], ['消',''], 'to vanish; to disappear; to be extinguished'),
  new Term(['き','こえる'], ['聞',''], 'to be audible; to be able to hear'),
  new Term(['きず','つける'], ['傷',''], 'to wound; to damage; to harm'),
  new Term(['き','める'], ['決',''], 'to decide'),
  new Term(['き','る'], ['着',''], 'to wear'),
  new Term(['き','れる'], ['切',''], 'to break; to cut off; to expire'),
  new Term(['きん','じる'], ['禁',''], 'to ban; to prohibit'),
  new Term(['くず','れる'], ['崩',''], 'to collapse; to cave in'),
  new Term(['くら','べる'], ['比',''], 'to compare'),
  new Term(['くる','しめる'], ['苦',''], 'to inflict pain; to torment'),
  new Term(['く','れる'], ['呉',''], 'to give'),
  new Term(['く','れる'], ['暮',''], 'to grow dark (at night)'),
  new Term(['くわ','える'], ['加',''], 'to add to; to include'),
  new Term(['くわだ','てる'], ['企',''], 'to plan; to scheme'),
  new Term(['こ','げる'], ['焦',''], 'to be burned; to become charred'),
  new Term(['こし','か','ける'], ['腰','掛',''], 'to sit (western style)'),
  new Term(['こしら','える'], ['拵',''], 'to make; to manufacture'),
  new Term(['こた','える'], ['答',''], 'to answer'),
  new Term(['こぼれる'], [''], 'to spill; to overflow'),
  new Term(['こわ','れる'], ['壊',''], 'to break'),
  new Term(['さ','ける'], ['避',''], 'to avoid; to dodge'),
  new Term(['さ','げる'], ['下',''], 'to lower; to hang'),
  new Term(['ささ','える'], ['支',''], 'to support'),
  new Term(['さだ','める'], ['定',''], 'to decide; to establish'),
  new Term(['さまた','げる'], ['妨',''], 'to hinder; to obstruct'),
  new Term(['し','める'], ['閉',''], 'to shut'),
  new Term(['し','らせる'], ['知',''], 'to notify'),
  new Term(['しら','べる'], ['調',''], 'to check; to investigate'),
  new Term(['しん','じる'], ['信',''], 'to believe; to trust'),
  new Term(['す','ぎる'], ['過',''], 'to pass; to exceed'),
  new Term(['すぐ','れる'], ['優',''], 'to excel; to be superior'),
  new Term(['す','てる'], ['捨',''], 'to discard; to throw away'),
  new Term(['そだ','てる'], ['育',''], 'to raise (a child); to rear'),
  new Term(['たお','れる'], ['倒',''], 'to fall down; to collapse'),
  new Term(['たくわ','える'], ['蓄',''], 'to set aside; to store'),
  new Term(['たす','ける'], ['助',''], 'to help'),
  new Term(['た','てる'], ['立',''], 'to build'),
  new Term(['た','べる'], ['食',''], 'to eat'),
  new Term(['た','める'], ['貯',''], 'to save; to accumulate'),
  new Term(['た','りる'], ['足',''], 'to suffice; to be enough'),
  new Term(['つか','れる'], ['疲',''], 'to become tired'),
  new Term(['つ','ける'], ['点',''], 'to turn on; to light'),
  new Term(['つづ','ける'], ['続',''], 'to continue; to proceed'),
  new Term(['つと','める'], ['勤',''], 'to work for'),
  new Term(['つよ','める'], ['強',''], 'to strengthen'),
  new Term(['つ','れる'], ['連',''], 'to lead'),
  new Term(['で','かける'], ['出',''], 'to go out; to leave the house'),
  new Term(['で','き','る'], ['出','来',''], 'to be able'),
  new Term(['で','る'], ['出',''], 'to leave; to come out'),
  new Term(['と','める'], ['止',''], 'to stop; to cease'),
  new Term(['と','り','か','える'], ['取','','換',''], 'to exchange; to replace'),
  new Term(['と','れる'], ['取',''], 'to come off; to be removed'),
  new Term(['なが','める'], ['眺',''], 'to watch; to view'),
  new Term(['なが','れる'], ['流',''], 'to flow'),
  new Term(['なぐさ','める'], ['慰',''], 'to comfort; to console'),
  new Term(['な','げる'], ['投',''], 'to throw; to cast away'),
  new Term(['なま','ける'], ['怠',''], 'to be idle; to laze'),
  new Term(['な','める'], ['舐',''], 'to lick'),
  new Term(['なら','べる'], ['並',''], 'to line up'),
  new Term(['な','れる'], ['慣',''], 'to get used to; to grow accustomed to'),
  new Term(['に','げる'], ['逃',''],  'to run away; to escape'),
  new Term(['に','る'], ['似',''], 'to resemble; to be similar to'),
  new Term(['ぬ','れる'], ['濡',''], 'to become wet'),
  new Term(['ね','る'], ['寝',''], 'to sleep; to go to bed'),
  new Term(['の','せる'], ['載',''], 'to place on top'),
  new Term(['の','り','か','える'], ['乗','','換',''], 'to transfer (as in public transportation)'),
  new Term(['はじ','める'], ['始',''], 'to begin'),
  new Term(['はず','れる'], ['外',''], 'to be disconnected; to get out of place'),
  new Term(['はな','れる'], ['離',''], 'to separate from; to leave'),
  new Term(['は','れる'], ['晴',''], 'to become sunny; to clear up (as in weather)'),
  new Term(['ひ','き','う','ける'], ['引','','受',''], 'to undertake; to take over'),
  new Term(['ひろ','める'], ['広',''], 'to propagate; to disseminate'),
  new Term(['ふ','える'], ['増',''], 'to increase'),
  new Term(['ふ','せる'], ['伏',''], 'to lie face down'),
  new Term(['ふ','れる'], ['触',''], 'to touch'),
  new Term(['ぶつける'], [''], 'to hit; to run into'),
  new Term(['ほど','ける'], ['解',''],  'to come untied; to loosen'),
  new Term(['ほ','める'], ['褒',''], 'to praise'),
  new Term(['ほ','れる'], ['惚',''], 'to fall in love; to be charmed'),
  new Term(['ま','ける'], ['負',''], 'to lose; to be defeated'),
  new Term(['ま','げる'], ['曲',''], 'to bend; to curve'),
  new Term(['ま','ぜる'], ['混',''],  'to mix'),
  new Term(['ま','ちが','える'], ['間','違',''], 'to make a mistake'),
  new Term(['み','える'], ['見',''], 'to be visible; to be able to see'),
  new Term(['み','せる'], ['見',''], 'to show'),
  new Term(['み','つける'], ['見',''], 'to find'),
  new Term(['みと','める'], ['認',''], 'to acknowledge; to admit; to recognize'),
  new Term(['み','る'], ['見',''], 'to look'),
  new Term(['むか','える'], ['迎',''], 'to go out to meet; to welcome'),
  new Term(['もう','ける'], ['儲',''], 'to profit; to make money'),
  new Term(['もてる'], [''], 'to be popular'),
  new Term(['もと','める'], ['求',''], 'to request; to ask; to seek'),
  new Term(['も','れる'], ['漏',''], 'to leak; to escape'),
  new Term(['や','ける'], ['焼',''], 'to burn'),
  new Term(['や','める'], ['辞',''], 'to stop; to give up; to resign'),
  new Term(['わか','れる'], ['別',''], 'to break up; to part from'),
  new Term(['わす','れる'], ['忘',''], 'to forget'),
];

var verbs_godan = [
  new Term(['あ','う'], ['会',''], 'to meet'),
  new Term(['あ','う'], ['合',''], 'to match; to fit'),
  new Term(['あお','ぐ'], ['仰',''], 'to look up; to seek'),
  new Term(['あ','がる'], ['上',''], 'to go up; to rise'),
  new Term(['あ','く'], ['開',''], 'to open; to become vacant'),
  new Term(['あせ','る'], ['焦',''], 'to be impatient; to be in a hurry'),
  new Term(['あそ','ぶ'], ['遊',''], 'to play'),
  new Term(['あたた','まる'], ['暖',''], 'to warm up'),
  new Term(['あつ','まる'], ['集',''], 'to gather; to assemble'),
  new Term(['あぶら','ぎる'], ['脂',''], 'to become greasy; to become oily'),
  new Term(['あら','う'], ['洗',''], 'to wash'),
  new Term(['ある','く'], ['歩',''], 'to walk'),
  new Term(['い','い','あらわ','す'], ['言','','表',''], 'to express (in words); to describe'),
  new Term(['い','い','か','える'], ['言','','換',''], 'to say in other words; to rephrase'),
  new Term(['い','い','だ','す'], ['言','','出',''], 'to start talking; to break the ice'),
  new Term(['い','いふらす'], ['言',''], 'to spread a rumor; to talk about'),
  new Term(['い','う'], ['言',''], 'to say'),
  new Term(['い','く'], ['行',''], 'to go'),
  new Term(['いそ','ぐ'], ['急',''], 'to hurry'),
  new Term(['いた','む'], ['痛',''], 'to hurt; to be injured'),
  new Term(['いつわ','る'], ['偽',''], 'to lie; to cheat; to deceive'),
  new Term(['いの','る'], ['祈',''], 'to pray; to wish for'),
  new Term(['い','ば','る'], ['威','張',''], 'to boast; to swagger'),
  new Term(['いや','がる'], ['嫌',''], 'to dislike; to hate'),
  new Term(['い','る'], ['要',''], 'to need'),
  new Term(['いわ','う'], ['祝',''], 'to celebrate; to congratulate'),
  new Term(['うご','く'], ['動',''], 'to move'),
  new Term(['うしな','う'], ['失',''], 'to lose; to part with'),
  new Term(['うた','う'], ['歌',''], 'to sing'),
  new Term(['う','る'], ['売',''], 'to sell'),
  new Term(['えら','ぶ'], ['選',''], 'to choose; to select'),
  new Term(['お','う'], ['追',''], 'to chase; to run after'),
  new Term(['お','く'], ['置',''], 'to put; to place'),
  new Term(['おく','る'], ['送',''], 'to send; to ship'),
  new Term(['お','こす'], ['起',''], 'to awaken (someone); to cause; to bring about'),
  new Term(['おこ','る'], ['怒',''], 'to get angry'),
  new Term(['お','こる'], ['起',''], 'to occur; to happen'),
  new Term(['お','しむ'], ['惜',''], 'to regret'),
  new Term(['お','す'], ['押',''], 'to push; to press'),
  new Term(['おそ','う'], ['襲',''], 'to attack'),
  new Term(['お','とす'], ['落',''], 'to drop; to let fall'),
  new Term(['おと','る'], ['劣',''], 'to be inferior; to fall behind'),
  new Term(['おど','る'], ['踊',''], 'to dance'),
  new Term(['おどろ','く'], ['驚',''], 'to be suprised; to be amazed'),
  new Term(['おも','いつく'], ['思',''], 'to conceive; to come up with'),
  new Term(['おも','う'], ['思',''], 'to think'),
  new Term(['およ','ぐ'], ['泳',''], 'to swim'),
  new Term(['およ','ぶ'], ['及',''], 'to extend; to reach'),
  new Term(['お','わる'], ['終',''], 'to end; to finish'),
  new Term(['か','う'], ['買',''], 'to buy'),
  new Term(['か','う'], ['飼',''], 'to keep (a pet); to raise; to rear'),
  new Term(['かえ','す'], ['返',''], 'to give back; to return (something to someone)'),
  new Term(['かえ','る'], ['帰',''], 'to return (home)'),
  new Term(['かじ','る'], ['齧',''], 'to gnaw; to nibble'),
  new Term(['か','かる'], ['掛',''], 'to take (a resource, e.g. time, money); to hang'),
  new Term(['かか','わる'], ['関',''], 'to be involved with; to concern oneself with'),
  new Term(['かがや','く'], ['輝',''], 'to shine; to sparkle'),
  new Term(['かぎ','る'], ['限',''], 'to limit'),
  new Term(['か','く'], ['書',''], 'to write'),
  new Term(['かく','す'], ['隠',''], 'to hide (something)'),
  new Term(['かく','れる'], ['隠',''], 'to hide (oneself)'),
  new Term(['かこ','む'], ['囲',''], 'to surround; to enclose'),
  new Term(['かさ','なる'], ['重',''], 'to overlap; to be piled up'),
  new Term(['かざ','る'], ['飾',''], 'to decorate; to display'),
  new Term(['か','す'], ['貸',''], 'to lend'),
  new Term(['かす','む'], ['霞',''], 'to grow hazy; to be misty'),
  new Term(['かせ','ぐ'], ['稼',''], 'to make money; to earn a living'),
  new Term(['かた','まる'], ['固',''], 'to harden; to solidify'),
  new Term(['かたむ','く'], ['傾',''], 'to lean towards; to tilt'),
  new Term(['か','つ'], ['勝',''], 'to win'),
  new Term(['かつ','ぐ'], ['担',''], 'to carry on one\'s shoulders'),
  new Term(['かな','う'], ['適',''], 'to be suited'),
  new Term(['かな','しむ'], ['悲',''], 'to be sad; to grieve'),
  new Term(['かば','う'], ['庇',''], 'to protect; to stick up for'),
  new Term(['かぶ','る'], ['被',''], 'to wear (on one\'s head)'),
  new Term(['かま','う'], ['構',''], 'to care about; to mind'),
  new Term(['か','む'], ['噛',''], 'to bite'),
  new Term(['かよ','う'], ['通',''], 'to commute'),
  new Term(['からかう'], [''], 'to tease; to mock'),
  new Term(['かわい','がる'], ['可愛',''], 'to be affectionate; to be fond of'),
  new Term(['かわ','かす'], ['乾',''], 'to dry; to dehydrate'),
  new Term(['かわ','く'], ['乾',''], 'to become dry'),
  new Term(['か','わる'], ['変',''], 'to change'),
  new Term(['がん','ば','る'], ['頑','張',''], 'to try one\'s best; to work hard'),
  new Term(['き','く'], ['聞',''], 'to listen'),
  new Term(['き','づか','う'], ['気','遣',''], 'to worry about; to consider'),
  new Term(['き','づ','く'], ['気','付',''], 'to sense; to notice; to realize'),
  new Term(['き','まる'], ['決',''], 'to be decided'),
  new Term(['き','る'], ['切',''], 'to cut'),
  new Term(['く','い','ちが','う'], ['食','','違',''], 'to differ; to clash'),
  new Term(['くさ','る'], ['腐',''], 'to decay; to go bad'),
  new Term(['くず','す'], ['崩',''], 'to destroy; to break down'),
  new Term(['くだ','く'], ['砕',''], 'to crush; to smash'),
  new Term(['く','ど','く'], ['口','説',''], 'to seduce; to make a play'),
  new Term(['く','む'], ['組',''], 'to put together; to assemble'),
  new Term(['くも','る'], ['曇',''], 'to become cloudy'),
  new Term(['く','らす'], ['暮',''], 'to live; to get along'),
  new Term(['くら','む'], ['眩',''], 'to be dazzled by; to be dizzied by'),
  new Term(['く','り','か','えす'], ['繰','','返',''], 'to repeat'),
  new Term(['くる','う'], ['狂',''], 'to go mad; to be out of order'),
  new Term(['くる','しむ'], ['苦',''], 'to suffer'),
  new Term(['け','す'], ['消',''], 'to erase; to turn off'),
  new Term(['け','る'], ['蹴',''], 'to kick'),
  new Term(['こころざ','す'], ['志',''], 'to aspire to'),
  new Term(['こ','す'], ['越','す'], 'to go across; to go over; to pass time'),
  new Term(['こと','なる'], ['異',''], 'to differ from'),
  new Term(['こと','わる'], ['断',''], 'to refuse; to decline'),
  new Term(['この','む'], ['好',''], 'to like; to prefer'),
  new Term(['こぼ','す'], ['零',''], 'to spill'),
  new Term(['こま','る'], ['困',''], 'to be troubled; to be bothered'),
  new Term(['こ','む'], ['込',''], 'to be crowded'),
  new Term(['こ','らす'], ['凝',''], 'to freeze; to congeal; to concentrate on'),
  new Term(['ころ','す'], ['殺',''], 'to kill'),
  new Term(['ころ','ぶ'], ['転',''], 'to fall down'),
  new Term(['こわ','がる'], ['怖',''], 'to fear'),
  new Term(['こわ','す'], ['壊',''], 'to smash; to break'),
  new Term(['さが','す'], ['探',''], 'to search for'),
  new Term(['さ','がる'], ['下',''], 'to hang down; to go down'),
  new Term(['さ','く'], ['咲','く'], 'to bloom'),
  new Term(['さ','す'], ['刺','す'], 'to sting; to stab; to pierce'),
  new Term(['さそ','う'], ['誘',''], 'to invite; to tempt'),
  new Term(['さわ','ぐ'], ['騒',''], 'to be rowdy; to make noise'),
  new Term(['さわ','る'], ['触',''], 'to touch or feel (with hands)'),
  new Term(['しか','る'], ['叱',''], 'to scold; to tell off'),
  new Term(['し','く'], ['敷',''], 'to spread out; to lay'),
  new Term(['しず','まる'], ['静',''], 'to grow quiet'),
  new Term(['しず','む'], ['沈',''], 'to sink; to feel depressed'),
  new Term(['し','ぬ'], ['死',''], 'to die'),
  new Term(['しば','る'], ['縛',''], 'to tie; to bind'),
  new Term(['し','まる'], ['閉',''], 'to be closed'),
  new Term(['しめ','す'], ['示',''], 'to indicate; to point out'),
  new Term(['しゃべ','る'], ['喋',''], 'to talk; to chat'),
  new Term(['し','る'], ['知',''], 'to know'),
  new Term(['じゅく','す'], ['熟',''], 'to ripen; to mature'),
  new Term(['す','う'], ['吸',''], 'to inhale; to sip; to smoke'),
  new Term(['す','く'], ['空',''], 'to become empty'),
  new Term(['すく','う'], ['救',''], 'to rescue; to save'),
  new Term(['すす','む'], ['進',''], 'to go forward; to advance'),
  new Term(['すべ','る'], ['滑',''], 'to slip'),
  new Term(['す','む'], ['住',''], 'to live; to reside'),
  new Term(['すわ','る'], ['座',''], 'to sit'),
  new Term(['そだ','つ'], ['育',''], 'to grow up; to be raised'),
  new Term(['たお','す'], ['倒',''], 'to overthrow; to knock down'),
  new Term(['たくら','む'], ['企',''], 'to plot; to scheme'),
  new Term(['たけ','る'], ['猛',''], 'to rage; to be fierce'),
  new Term(['た','す'], ['足',''], 'to add'),
  new Term(['たた','む'], ['畳',''], 'to fold'),
  new Term(['た','つ'], ['立',''], 'to stand up'),
  new Term(['たの','しむ'], ['楽',''], 'to enjoy; to have fun'),
  new Term(['たの','む'], ['頼',''], 'to ask; to beg; to implore'),
  new Term(['た','まる'], ['貯',''], 'to be saved; to be accumulated'),
  new Term(['ため','す'], ['試',''], 'to test; to try'),
  new Term(['だ','く'], ['抱',''], 'to embrace; to hug'),
  new Term(['だ','す'], ['出',''], 'to put out; to produce'),
  new Term(['だま','す'], ['騙',''], 'to trick; to deceive'),
  new Term(['だま','る'], ['黙',''], 'to shut up; to stop talking'),
  new Term(['ちが','う'], ['違',''], 'to be wrong; to be different'),
  new Term(['ち','る'], ['散',''], 'to scatter; to fall'),
  new Term(['つか','う'], ['使',''], 'to use; to operate'),
  new Term(['つ','く'], ['着',''], 'to arrive'),
  new Term(['つく','る'], ['作',''], 'to make; to build; to create'),
  new Term(['つ','ぐ'], ['次',''], 'to be next'),
  new Term(['つつ','む'], ['包',''], 'to wrap'),
  new Term(['つづ','く'], ['続',''], 'to continue; to follow'),
  new Term(['つよ','まる'], ['強',''], 'to become stronger'),
  new Term(['つ','る'], ['釣',''], 'to fish'),
  new Term(['て','つだ','う'], ['手','伝',''], 'to help'),
  new Term(['とど','く'], ['届',''], 'to reach'),
  new Term(['と','ぶ'], ['飛',''], 'to jump; to fly'),
  new Term(['と','まる'], ['止',''], 'to stop'),
  new Term(['と','る'], ['取',''], 'to take'),
  new Term(['なお','す'], ['直',''], 'to cure; to heal; to repair'),
  new Term(['なお','る'], ['治',''], 'to be cured; to be healed'),
  new Term(['なが','す'], ['流',''], 'to flow; to drain; to pour'),
  new Term(['な','く'], ['鳴',''], 'to bark; to purr'),
  new Term(['な','く'], ['泣',''], 'to cry'),
  new Term(['な','くす'], ['無',''], 'to lose; to get rid of'),
  new Term(['な','くなる'], ['無',''], 'to go missing; to vanish'),
  new Term(['なぐ','る'], ['殴',''], 'to punch; to hit'),
  new Term(['な','じ','む'], ['馴','染',''], 'to become familiar with; to adapt'),
  new Term(['なら','う'], ['習',''], 'to learn'),
  new Term(['なら','ぶ'], ['並',''], 'to form a line'),
  new Term(['な','る'], ['成',''], 'to become'),
  new Term(['にぎ','る'], ['握',''], 'to grasp'),
  new Term(['にら','む'], ['睨',''], 'to glare at; to keep an eye on'),
  new Term(['ぬ','ぐ'], ['脱',''], 'to remove'),
  new Term(['ぬぐ'], ['脱ぐ'], 'to take off, remove (shoes, clothes)'),
  new Term(['ぬす','む'], ['盗',''], 'to steal'),
  new Term(['ぬ','る'], ['塗',''], 'to paint'),
  new Term(['ね','じる'], ['捩',''], 'to twist'),
  new Term(['ねむ','る'], ['眠',''], 'to fall asleep'),
  new Term(['のこ','す'], ['残',''], 'to leave behind; to save'),
  new Term(['のこ','る'], ['残',''], 'to be left over; to remain'),
  new Term(['ののし','る'], ['罵',''], 'to abuse; to speak ill of'),
  new Term(['の','ばす'], ['延',''], 'to extend; to prolong'),
  new Term(['のぼ','る'], ['登',''], 'to climb'),
  new Term(['の','む'], ['飲',''], 'to drink'),
  new Term(['の','る'], ['乗',''], 'to board; to ride on'),
  new Term(['はい','る'], ['入',''], 'to enter'),
  new Term(['は','く'], ['履',''], 'to wear (on feet or legs, e.g. trousers, shoes)'),
  new Term(['はげ','ます'], ['励',''], 'to encourage'),
  new Term(['はげ','む'], ['励',''], 'to endeavor'),
  new Term(['はこ','ぶ'], ['運',''], 'to carry'),
  new Term(['はさ','む'], ['挟',''], 'to interpose; to intervene'),
  new Term(['はし','る'], ['走',''], 'to run'),
  new Term(['はじ','まる'], ['始',''], 'to begin'),
  new Term(['はず','す'], ['外',''], 'to remove; to unfasten'),
  new Term(['はたら','く'], ['働',''], 'to work'),
  new Term(['はな','し','あ','う'], ['話','','合',''], 'to discuss'),
  new Term(['はな','す'], ['話',''], 'to speak'),
  new Term(['はべ','る'], ['侍',''], 'to serve; to wait upon'),
  new Term(['は','や','る'], ['流','行',''], 'to become popular; to come into fashion'),
  new Term(['はら','う'], ['払',''], 'to pay'),
  new Term(['は','る'], ['貼',''], 'to stick; to paste on'),
  new Term(['ひか','る'], ['光',''], 'to shine; to shimmer'),
  new Term(['ひ','く'], ['引',''], 'to pull'),
  new Term(['ひ','く'], ['弾',''], 'to play (a string instrument)'),
  new Term(['ひ','やかす'], ['冷',''], 'to jeer; to make fun; to chill'),
  new Term(['ひ','やす'], ['冷',''], 'to cool; to refrigerate'),
  new Term(['ひら','く'], ['開',''], 'to open; to hold an event'),
  new Term(['ひろ','う'], ['拾',''], 'to pick up; to find'),
  new Term(['ひろ','まる'], ['広',''], 'to spread; to expand'),
  new Term(['びびる'], [''], 'to be surprised'),
  new Term(['ふ','く'], ['吹',''], 'to blow'),
  new Term(['ふ','せる'], ['臥',''], 'to lie down'),
  new Term(['ふと','る'], ['太',''], 'to get fat; to put on weight'),
  new Term(['ふ','む'], ['踏',''], 'to step on'),
  new Term(['ふ','る'], ['降',''], 'to fall from the sky (e.g. rain)'),
  new Term(['ぶつかる'], [''], 'to hit; to run into'),
  new Term(['へ','らす'], ['減',''], 'to abate; to decrease; to diminish'),
  new Term(['へ','る'], ['減',''], 'to reduce; to decrease'),
  new Term(['ほ','しがる'], ['欲',''], 'to want; to desire'),
  new Term(['ほ','す'], ['干',''], 'to dry; to air'),
  new Term(['ほど','く'], ['解',''], 'to solve; to answer; to untie'),
  new Term(['ほの','めかす'], ['仄',''], 'to hint; to allude'),
  new Term(['ほ','る'], ['掘',''], 'to dig'),
  new Term(['ほろ','びる'], ['滅',''], 'to perish'),
  new Term(['ほろ','ぼす'], ['滅',''], 'to destroy; to ruin'),
  new Term(['まい','る'], ['参',''], 'to come (humble); to visit'),
  new Term(['ま','かす'], ['負',''], 'to defeat'),
  new Term(['ま','がる'], ['曲',''], 'to turn; to bend'),
  new Term(['ま','じる'], ['混',''], 'to be mixed'),
  new Term(['ま','ちが','う'], ['間','違',''], 'to be mistake; to make a mistake'),
  new Term(['ま','つ'], ['待',''], 'to wait'),
  new Term(['まつ','る'], ['祀',''], 'to worship'),
  new Term(['まな','ぶ'], ['学',''], 'to learn; to study'),
  new Term(['まね','く'], ['招',''], 'to invite; to beckon to'),
  new Term(['まも','る'], ['守',''], 'to protect'),
  new Term(['まよ','う'], ['迷',''], 'to get lost; to go astray; to be puzzled'),
  new Term(['まわ','る'], ['回',''], 'to go round'),
  new Term(['みが','く'], ['磨',''], 'to polish'),
  new Term(['み','つかる'], ['見',''], 'to be found'),
  new Term(['み','な','す'], ['見','做',''], 'to look upon; to consider'),
  new Term(['み','のが','す'], ['見','逃',''], 'to overlook'),
  new Term(['みの','る'], ['実',''], 'to ripen; to bear fruit'),
  new Term(['み','は','る'], ['見','張',''], 'to stand guard; to keep a lookout'),
  new Term(['む','かう'], ['向',''], 'to face; to turn towards; to head towards'),
  new Term(['むす','ぶ'], ['結',''], 'to tie; to bind'),
  new Term(['め','だ','つ'], ['目','立',''], 'to attract attention; to stand out'),
  new Term(['もう','かる'], ['儲',''], 'to be profitable; to make money'),
  new Term(['も','つ'], ['持',''], 'to have; to hold; to own'),
  new Term(['もと','づく'], ['基',''], 'to be based on'),
  new Term(['もど','す'], ['戻',''], 'to return (a thing); to restore; to put back'),
  new Term(['もど','る'], ['戻',''], 'to return (to a place); to go back'),
  new Term(['もら','う'], ['貰',''], 'to receive; to get'),
  new Term(['も','らす'], ['漏',''], 'to leak; to disclose'),
  new Term(['や','く'], ['焼',''], 'to bake; to grill'),
  new Term(['やす','む'], ['休',''], 'to rest; to sleep'),
  new Term(['やる'], [''], 'to do; to give'),
  new Term(['よ','ぶ'], ['呼',''], 'to call'),
  new Term(['よ','む'], ['読',''], 'to read'),
  new Term(['よろこ','ぶ'], ['喜',''], 'to be pleased; to be glad'),
  new Term(['わ','かる'], ['分',''], 'to understand'),
  new Term(['わた','す'], ['渡',''], 'to hand over'),
  new Term(['わた','る'], ['渡',''], 'to cross'),
  new Term(['わらう'], ['笑',''], 'to laugh'),
];

var adjective_i = [
  new Term(['あお','い'], ['青',''], 'blue'),
  new Term(['あか','い'], ['赤',''], 'red'),
  new Term(['あか','るい'], ['明',''], 'bright'),
  new Term(['あたた','かい'], ['温',''], 'warm'),
  new Term(['あたら','しい'], ['新',''], 'new'),
  new Term(['あつ','い'], ['暑',''], 'hot'),
  new Term(['あぶ','ない'], ['危',''], 'dangerous'),
  new Term(['あま','い'], ['甘',''], 'sweet'),
  new Term(['いそが','しい'], ['忙',''], 'busy'),
  new Term(['いた','い'], ['痛',''], 'painful'),
  new Term(['うす','い'], ['薄',''], 'thin; faint'),
  new Term(['おい','しい'], ['美味',''], 'delicious'),
  new Term(['おお','きい'], ['大',''], 'big'),
  new Term(['おそ','い'], ['遅',''], 'late, slow'),
  new Term(['おも','い'], ['重',''], 'heavy'),
  new Term(['おも','しろ','い'], ['面','白',''], 'interesting; funny'),
  new Term(['から','い'], ['辛',''], 'hot, spicy'),
  new Term(['かる','い'], ['軽',''], 'light (not heavy)'),
  new Term(['かわい','い'], ['可愛',''], 'cute, pretty'),
  new Term(['き','いろ','い'], ['黄','色','い'], 'yellow'),
  new Term(['きたな','い'], ['汚',''], 'dirty'),
  new Term(['きび','しい'], ['厳',''], 'strict'),
  new Term(['くら','い'], ['暗',''], 'dark'),
  new Term(['くろ','い'], ['黒',''], 'black'),
  new Term(['こわ','い'], ['怖',''], 'friightening'),
  new Term(['さび','しい'], ['寂',''], 'lonely'),
  new Term(['さむ','い'], ['寒',''], 'cold'),
  new Term(['しろ','い'], ['白',''], 'white'),
  new Term(['すご','い'], ['凄',''], 'terrific'),
  new Term(['すず','しい'], ['涼',''], 'cool; refreshing'),
  new Term(['す','ば','らしい'], ['素','晴',''], 'wonderful'),
  new Term(['せま','い'], ['狭',''], 'narrow'),
  new Term(['たか','い'], ['高',''], 'expensive, high, tall'),
  new Term(['ただ','しい'], ['正',''], 'correct'),
  new Term(['たの','しい'], ['楽',''], 'enjoyable, fun'),
  new Term(['ちい','さい'], ['小',''], 'small'),
  new Term(['ちか','い'], ['近',''], 'near, close'),
  new Term(['つま','らない'], ['詰',''], 'uninteresting'),
  new Term(['つめ','たい'], ['冷',''], 'cold'),
  new Term(['つよ','い'], ['強',''], 'strong'),
  new Term(['なが','い'], ['長',''], 'long'),
  new Term(['にが','い'], ['苦',''], 'bitter'),
  new Term(['ねむ','い'], ['眠',''], 'sleepy'),
  new Term(['はや','い'], ['早',''], 'early'),
  new Term(['はや','い'], ['速',''], 'fast'),
  new Term(['ひく','い'], ['低',''], 'low'),
  new Term(['ひど','い'], ['酷',''], 'terrible; cruel'),
  new Term(['ひろ','い'], ['広',''], 'wide'),
  new Term(['ふか','い'], ['深',''], 'deep'),
  new Term(['ふと','い'], ['太',''], 'fat; thick'),
  new Term(['ふる','い'], ['古',''], 'old'),
  new Term(['ほそ','い'], ['細',''], 'fine; thin'),
  new Term(['まず','い'], ['不味','い'], 'unpalatable; bad tasting'),
  new Term(['まる','い'], ['丸',''], 'round'),
  new Term(['みじか','い'], ['短',''], 'short'),
  new Term(['むずか','しい'], ['難',''], 'difficult'),
  new Term(['めずら','しい'], ['珍',''], 'rare'),
  new Term(['やさ','しい'], ['優',''], 'gentle; kind'),
  new Term(['やす','い'], ['安',''], 'cheap'),
  new Term(['やす','い'], ['易',''], 'easy'),
  new Term(['やわら','かい'], ['柔',''], 'soft; tender'),
  new Term(['わか','い'], ['若',''], 'young'),
];

var adjective_na = [
  new Term(['いっしょう','けん','めい'], ['一生','懸','命'], 'with all one\'s might, with utmost effort'),
  new Term(['いや'], ['嫌'], 'unpleasant; disagreeable'),
  new Term(['いろいろ'], ['色々'], 'various'),
  new Term(['おお','ぜい'], ['大','勢'], 'crowded; a large number (e.g. of people)'),
  new Term(['かん','たん'], ['簡','単'], 'easy; simple'),
  new Term(['き','けん'], ['危','険'], 'dangerous'),
  new Term(['きら','い'], ['嫌い'], 'disliked'),
  new Term(['き','れい'], ['綺','麗'], 'pretty; beautiful'),
  new Term(['けっこう'], ['結構'], 'wonderful; splendid'),
  new Term(['げん','き'], ['元','気'], 'healthy; robust'),
  new Term(['ざん','ねん'], ['残念'], 'regrettable; disappointing'),
  new Term(['しず','か'], ['静',''], 'quiet'),
  new Term(['しん','ぱい'], ['心','配'], 'worry; concern'),
  new Term(['じゅう','ぶん'], ['十','分'], 'sufficient; satisfactory'),
  new Term(['じ','ゆう'], ['自','由'], 'free; unrestrained'),
  new Term(['じょう','ず'], ['上','手'], 'proficient; skillful'),
  new Term(['じょう','ぶ'], ['丈','夫'], 'sturdy; strong; solid'),
  new Term(['す','き'], ['好',''], 'liked'),
  new Term(['たい','せつ'], ['大','切'], 'important; precious'),
  new Term(['たい','へん'], ['大','変'], 'terrible; dreadful; very'),
  new Term(['だい','じょう','ぶ'], ['大','丈','夫'], 'fine; all right'),
  new Term(['だい','す','き'], ['大','好',''], 'very liked; loved'),
  new Term(['てい','ねい'], ['丁','寧'], 'polite; courteous'),
  new Term(['てき','とう'], ['適','当'], 'suitable; proper'),
  new Term(['とく','べつ'], ['特','別'], 'special'),
  new Term(['にぎ','やか'], ['賑',''], 'lively'),
  new Term(['ねっしん'], ['熱心'], 'eager; enthusiastic'),
  new Term(['ひつ','よう'], ['必','要'], 'necessary'),
  new Term(['ひま'], ['暇'], 'free (time)'),
  new Term(['ふ','べん'], ['不','便'], 'inconvenient'),
  new Term(['へ','た'], ['下','手'], 'unskillful; inept'),
  new Term(['べん','り'], ['便','利'], 'useful; convenient'),
  new Term(['ま','じ','め'], ['真','面','目'], 'serious; earnest'),
  new Term(['ま','っ','す','ぐ'], ['真','','直',''], 'straight; direct'),
  new Term(['む','り'], ['無','理'], 'unreasonable; impossible'),
  new Term(['ゆう','めい'], ['有','名'], 'famous'),
  new Term(['らく'], ['楽'], 'comfortable; easy'),
  new Term(['りっぱ'], ['立派'], 'fine; splendid; handsome'),
];
